export const events = [
    {
        eventcode: "24323423423",
        image: "https://mdbcdn.b-cdn.net/img/Photos/Horizontal/E-commerce/Products/img%20(4).webp",
        eventname: "wedding",
        rating: 3,
        numberofBooking: 12,
        Culture: "Hindu",
        description: "lofgsgsfdgsdfgdfg",
        Price: 1234.4545,
        Prioed: "2days",
        subTotal: 35000,
        relatedServices:23
    },
    {
        eventcode: "24323423423",
        image: "https://mdbcdn.b-cdn.net/img/Photos/Horizontal/E-commerce/Products/img%20(4).webp",
        eventname: "wedding",
        rating: 3,
        numberofBooking: 12,
        Culture: "Hindu",
        description: "lofgsgsfdgsdfgdfg",
        Price: 1234.4545,
        Prioed: "2days",
        subTotal: 35000,
        relatedServices:23
    },
    {
        eventcode: "24323423423",
        image: "https://mdbcdn.b-cdn.net/img/Photos/Horizontal/E-commerce/Products/img%20(4).webp",
        eventname: "wedding",
        rating: 3,
        numberofBooking: 12,
        Culture: "Hindu",
        description: "lofgsgsfdgsdfgdfg",
        Price: 1234.4545,
        Prioed: "2days",
        subTotal: 35000,
        relatedServices:23
    },
    {
        eventcode: "24323423423",
        image: "https://mdbcdn.b-cdn.net/img/Photos/Horizontal/E-commerce/Products/img%20(4).webp",
        eventname: "wedding",
        rating: 3,
        numberofBooking: 12,
        Culture: "Hindu",
        description: "lofgsgsfdgsdfgdfg",
        Price: 1234.4545,
        Prioed: "2days",
        subTotal: 35000,
        relatedServices:23
    },
    {
        eventcode: "24323423423",
        image: "https://mdbcdn.b-cdn.net/img/Photos/Horizontal/E-commerce/Products/img%20(4).webp",
        eventname: "wedding",
        rating: 3,
        numberofBooking: 12,
        Culture: "Hindu",
        description: "lofgsgsfdgsdfgdfg",
        Price: 1234.4545,
        Prioed: "2days",
        subTotal: 35000,
        relatedServices:23
    },
    {
        eventcode: "24323423423",
        image: "https://mdbcdn.b-cdn.net/img/Photos/Horizontal/E-commerce/Products/img%20(4).webp",
        eventname: "wedding",
        rating: 3,
        numberofBooking: 12,
        Culture: "Hindu",
        description: "lofgsgsfdgsdfgdfg",
        Price: 1234.4545,
        Prioed: "2days",
        subTotal: 35000,
        relatedServices:23
    },
    {
        eventcode: "24323423423",
        image: "https://mdbcdn.b-cdn.net/img/Photos/Horizontal/E-commerce/Products/img%20(4).webp",
        eventname: "wedding",
        rating: 3,
        numberofBooking: 12,
        Culture: "Hindu",
        description: "lofgsgsfdgsdfgdfg",
        Price: 1234.4545,
        Prioed: "2days",
        subTotal: 35000,
        relatedServices:23
    }
]